
export const LOAD_TTITLE_LESSONS = 'LOAD_TTITLE_LESSONS'
export const LOAD_TASK_FOR_LESSON = 'LOAD_TASK_FOR_LESSON'
export const INCREMENT_CURRENT_TASK = 'INCREMENT_CURRENT_TASK'
export const INIT_CURRENT_TASK = 'INIT_CURRENT_TASK'
export const INCREMENT_COUNT_RIGHT_ANSWERS = 'INCREMENT_COUNT_RIGHT_ANSWERS'
export const INIT_COUNT_RIGHT_ANSWERS = 'INIT_COUNT_RIGHT_ANSWERS'

export const INCREMENT_COUNT_POINTS = 'INCREMENT_COUNT_POINTS'
export const INIT_COUNT_POINTS = 'INIT_COUNT_POINTS'

export const INCREMENT_COUNT_COINS = 'INCREMENT_COUNT_COINS'
export const INIT_COUNT_COINS = 'INIT_COUNT_COINS'

export const ENABLE_TIP = 'ENABLE_TIP'
export const DISABLE_TIP = 'DISABLE_TIP'
